Migrate coverage test (#570)
Convert the coverage test to be a bazel test rather than a bash one.
Added the ability to have post bazel run script parts to support testing the
bazel outputs.

diff --git a/tests/coverage/BUILD b/tests/coverage/BUILD
--- a/tests/coverage/BUILD
+++ b/tests/coverage/BUILD
@@ -1,4 +1,7 @@
-load("@io_bazel_rules_go//go:def.bzl", "go_library", "go_test")
+load("@io_bazel_rules_go//go:def.bzl", "go_library", "go_test", "go_prefix")
+load("@io_bazel_rules_go//tests:bazel_tests.bzl", "bazel_test")
+
+go_prefix("github.com/bazelbuild/rules_go/tests/coverage")
 
 go_test(
     name = "go_default_test",
@@ -11,4 +14,16 @@ go_test(
 go_library(
     name = "go_default_library",
     srcs = ["lib.go"],
+)
+
+bazel_test(
+    name = "coverage",
+    command = "coverage",
+    target = "//:go_default_test",
+    check = """
+if ! grep -q '^coverage: 50.0% of statements' "bazel-testlogs/go_default_test/test.log"; then
+  echo "error: no coverage output found in test log file" >&2
+  exit 1
+fi
+    """
 )
