Fix coverage bug with go_binary (#642)
Coverage is now applied in emit_library_actions instead of
emit_go_compile_action. emit_library_actions accepts a want_coverage
parameter, which is only true for go_library. go_test and go_binary
should not apply coverage to their own sources, but will continue to
apply coverage to sources from the library attribute.

In the future, we may want to apply coverage before running cgo
(#641), so this provides an easy way to prevent coverage being applied
a second time in go_library.

Fixes #629

diff --git a/tests/coverage/BUILD b/tests/coverage/BUILD
--- a/tests/coverage/BUILD
+++ b/tests/coverage/BUILD
@@ -1,4 +1,4 @@
-load("@io_bazel_rules_go//go:def.bzl", "go_library", "go_test", "go_prefix")
+load("@io_bazel_rules_go//go:def.bzl", "go_binary", "go_library", "go_test", "go_prefix")
 load("@io_bazel_rules_go//tests:bazel_tests.bzl", "bazel_test")
 
 go_prefix("github.com/bazelbuild/rules_go/tests/coverage")
@@ -27,3 +27,29 @@ if ! grep -q '^coverage: 50.0% of statements' "bazel-testlogs/go_default_test/te
 fi
     """
 )
+
+go_binary(
+    name = "bin",
+    srcs = ["bin.go"],
+    library = ":bin_lib",
+)
+
+go_library(
+    name = "bin_lib",
+    srcs = ["bin_lib.go"],
+)
+
+bazel_test(
+    name = "bin_coverage",
+    command = "coverage",
+    target = "//:bin",
+    check = """
+no_tests_found=4
+if [ "$result" -ne "$no_tests_found" ]; then
+  echo "error: unexpected bazel exit code: want $no_tests_found, got $result" >&2
+  exit 1
+fi
+result=0
+""",
+)
+
